apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # FIXME: Change the URL to the internal DNS name of the Prometheus server
    url: http://prometheus.{名前}-mlops-practice.internal:9090
    isDefault: true
