{
 "title": "Sample Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Software Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ecs_cpu_seconds_total{container=\"predictor\"}[1m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(ecs_cpu_seconds_total{container=\"predictor-canary\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(ecs_memory_bytes{container=\"predictor\"}) / sum(ecs_memory_limit_bytes{container=\"predictor\"}) * 1000000000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(ecs_memory_bytes{container=\"predictor-canary\"}) / sum(ecs_memory_limit_bytes{container=\"predictor-canary\"}) * 1000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ML Pipeline Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(evaluate_metrics{metric=\"accuracy\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AUC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg(evaluate_metrics{metric=\"auc\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "logloss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(evaluate_metrics{metric=\"logloss\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "precision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg(evaluate_metrics{metric=\"precision\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg(evaluate_metrics{metric=\"recall\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "calibration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "avg(evaluate_metrics{metric=\"calibration\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Train Data Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Train Data Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "data_amount{dataset=\"train\",model_name=\"sgd_classifier_ctr_model\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_amount{dataset=\"train\",model_name=\"sgd_classifier_ctr_optuna_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Valid Data Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "data_amount{dataset=\"valid\",model_name=\"sgd_classifier_ctr_model\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_amount{dataset=\"valid\",model_name=\"sgd_classifier_ctr_optuna_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Data Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "data_amount{dataset=\"test\",model_name=\"sgd_classifier_ctr_model\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "data_amount{dataset=\"test\",model_name=\"sgd_classifier_ctr_optuna_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "click",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(data_distribution{column=\"click\"}) by (value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(data_distribution{column=\"hour\"}) by (value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "request_count_total{env=\"predictor\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "request_count_total{env=\"predictor-canary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "2xx request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "request_count_total{env=\"predictor\", status_code=\"2xx\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "request_count_total {env=\"predictor-canary\", status_code=\"2xx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4xx request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "request_count_total {env=\"predictor\", status_code=\"4xx\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "request_count_total {env=\"predictor-canary\", status_code=\"4xx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "5xx request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "request_count_total {env=\"predictor\", status_code=\"5xx\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "request_count_total {env=\"predictor-canary\", status_code=\"5xx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eCTR",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "prediction_value{model_name=\"sgd_classifier_ctr_model\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "prediction_value{model_name=\"sgd_classifier_ctr_optuna_model\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avarage Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "response_time_seconds_count{env=\"predictor\", instance=\"unknown\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}