{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(request_count_total{env=\"predictor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AUC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(evaluate_metrics{metric=\"auc\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Click Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(data_distribution{column=\"click\"}) by (value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(data_amount) by (dataset)", "legendFormat": "__auto" }
   ]
  }
 ]
}