FROM public.ecr.aws/lambda/python:3.11

COPY requirements/importer.txt requirements/importer.txt
RUN pip install --no-cache-dir -r requirements/importer.txt

COPY ./importer/main.py ./

CMD [ "main.handler" ]
