FROM fluent/fluentd:v1.16-2
USER root

RUN apk --update-cache add tzdata && \
    gem install fluent-plugin-s3 -v 1.7.2 --no-document && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*

COPY ./fluentd/ecs /fluentd/etc
